name: 'Slack notification'
description: 'Sends notification to Slack'
inputs:
  channel-url:
    description: 'Github token'
    required: true
  status:
    description: 'Workflow status'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
